# Generated by Django 2.1.15 on 2020-05-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200502_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('AUTHOR', 'author'), ('EDITOR', 'editor'), ('PUBLISHER', 'publisher'), ('SUPERVISOR', 'supervisor'), ('ADMIN', 'admin')], default='student', max_length=64),
        ),
    ]
