# Generated by Django 2.1.15 on 2020-05-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200505_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'permissions': (('can_approve_or_reject_tweet', 'Can approve or reject tweets'),)},
        ),
    ]
